branch-defaults:
  master:
    environment: ItaisWebApplication-dev
    group_suffix: null
deploy:
  artifact: target/ItaisWebApp-0.0.1-SNAPSHOT.jar
global:
  application_name: ItaisWebApplication
  branch: null
  default_ec2_keyname: aws_key
  default_platform: Java 8
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
